[tool.poetry]
name = "mlb-team-employee-database"
version = "0.1.0"
description = ""
authors = ["Brian Barnes <brianbarnes@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
